apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: redhat-sso
    mappingMethod: claim 
    openID:
      claims:
        email:
          - email
        name:
          - name
        preferredUsername:
          - email
      clientID: 35776496954-t09ldpfqtsdcmeo29momtfs6inmelcbi.apps.googleusercontent.com
      clientSecret:
        name: goog-auth
      extraScopes:
        - profile
        - email
      issuer: 'https://accounts.google.com'
    type: OpenID
