kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bry-clusteradmin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: bjarvis@redhat.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
